VAGRANTFILE_API_VERSION = "2"

VM_IP = "10.10.10.10"
CASS_VER = "21x"
ES_VER = "1.5.2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, path: "bootstrap.sh", args: [VM_IP, CASS_VER, ES_VER]
  config.vm.network "private_network", ip: VM_IP

  config.vm.provider "virtualbox" do |vb|
	    vb.memory = 2048
		  vb.cpus = 2
  end
 end
